language: ruby
rvm:
- 2.1
install: gem install jekyll jekyll-sitemap jekyll-paginate redcarpet html-proofer
before_script: chmod +x build.sh deploy.sh
script: bash ./build.sh
after_success: bash ./deploy.sh
notifications:
  email:
  - p@singularityu.org
  on_success: always
  on_failure: always
  slack:
    secure: RcEEQgq+dvWpurZsGZ0gR06/frOtozUHu2PQvHffj0BuF80SE++60pnduKtF++L52njOt3IEgllG1P6NTL9yio0zVEhUD5giF6fHXW73SHXsEz6X1yMbQid3WHXOXP7U5ddOixeNNu50UkLBMerEOFVQt1qV+RddE9+Bbs+YglN23slZKzBgCXlGGRi+Jf3cVLhFrZsPAiU5wrokzwCxUKihWlxjyfIBzCYegXaVeTs5kTRvBbj6bPQWfXNUR9DjNdfNCDJWmwlqRbiPlK7uSLaa1b3kb5nQKMv9l8VApy7e2+Zm2DTC2ymQogJglXuh3RwWVnatL/e3XwO+BY7wrIG9XG0QqOeae3nZ47EO7sKxiOQWllfCo+KpmUOpYmY/nQ9ToDpjLsvhdKaUWTdi2Au87vUS77mkRBw18k1YlU/iNrgYNEpqJeowO/YmEhkAgOY9WWFqpjd+izT3C+/6JJoNxTGBa43pGIu2pmRm/sefD3XkhATGgFb+XlgIdPikWaywzqQZj9gLCTi3CWJEd0cUzxfQkgwDaOUo0z/dQ2/+OA1FEg8LxUrb5cjJoiarm4jmuRMSIVFLg+ns1+mseHeB41Lwjc0tjWCx0rpwm9X7kRvd8efow0/FwLt9wfmhXq9aV6SMEAb++WYlYcf8wE5bEqURWbfBM/NVtHIMP9c=
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GH_STAGING: github.com/SingularityUniversity/startup-staging.git
  - GH_PRODUCTION: github.com/SingularityUniversity/startup.git
  - CNAME_STAGING: staging-startup.singularityu.org
  - CNAME_PRODUCTION: startup.singularityu.org
  - secure: K7lRLF6h2p/VDSAZHMTMJ5REa7+weVVq4+Ki9XBpoMfqOk0ZydG+umupjKVeKqwfU500nRb1htX43WeckqqSHwQxVTnQhcO0qnvuYj0IwgUYRRQT8p0DDcUA3z3n9QgnhcqHgdPIoVdgYVo9xSKwQCqpw4KD4BHXNNuC2Hbg8Foo/GpPcrgjCURMDXlqWaHklAvSUWSrLjSKFVxqo3efN+SVo3wNDAJQY0qcSRGC2CwTM+QiGXb9Wa+DyOrHT7OWWpWPGvlHcmfe2KH8jq6+68TXcQ7TVhpRpOUPrlIhcAuLz9WVQgNAEf4MvQOvTPAY5R0cWeFC41UYrz/x50xRe65nuARTxaM3MALGdjjDodNuAVMlLPNPLEQQgDXWEHrbTtKWi19VIvK0GxqHLAVklEV0h6tTI4QxJFvAQ9u6i1/ykVkU/CgtF7VfEgaZZjXEZEn29ophOF1gjnV6f6GR4RYscDWvZ2tJPPLjIz9jVJ9L0xcFm2sJALy8CvFBCY34HfyCbNFgZjXX2A5WLPTbLLOV2OOGHjuR6TACIzamjZDxBGah3R1bB+7vEFs+Y0CA+HIkHbi0W6V8cxjP+Gonj4Su9ChcG8ItrkBsbkpsqJu8JJKiMCvDzlaF+Rd1I8CKdnvlfSPfcAZO6kOqnLSCLjVmN64oaBgi8jv7xNFu5+c=
