language: ruby
rvm:
- 2.1
install: gem install jekyll jekyll-sitemap html-proofer
script: bash ./deploy.sh
notifications:
  email:
  - p@singularityu.org
  on_success: always
  on_failure: always
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GH_REF: github.com/SingularityUniversity/startup-staging.git
  - secure: K7lRLF6h2p/VDSAZHMTMJ5REa7+weVVq4+Ki9XBpoMfqOk0ZydG+umupjKVeKqwfU500nRb1htX43WeckqqSHwQxVTnQhcO0qnvuYj0IwgUYRRQT8p0DDcUA3z3n9QgnhcqHgdPIoVdgYVo9xSKwQCqpw4KD4BHXNNuC2Hbg8Foo/GpPcrgjCURMDXlqWaHklAvSUWSrLjSKFVxqo3efN+SVo3wNDAJQY0qcSRGC2CwTM+QiGXb9Wa+DyOrHT7OWWpWPGvlHcmfe2KH8jq6+68TXcQ7TVhpRpOUPrlIhcAuLz9WVQgNAEf4MvQOvTPAY5R0cWeFC41UYrz/x50xRe65nuARTxaM3MALGdjjDodNuAVMlLPNPLEQQgDXWEHrbTtKWi19VIvK0GxqHLAVklEV0h6tTI4QxJFvAQ9u6i1/ykVkU/CgtF7VfEgaZZjXEZEn29ophOF1gjnV6f6GR4RYscDWvZ2tJPPLjIz9jVJ9L0xcFm2sJALy8CvFBCY34HfyCbNFgZjXX2A5WLPTbLLOV2OOGHjuR6TACIzamjZDxBGah3R1bB+7vEFs+Y0CA+HIkHbi0W6V8cxjP+Gonj4Su9ChcG8ItrkBsbkpsqJu8JJKiMCvDzlaF+Rd1I8CKdnvlfSPfcAZO6kOqnLSCLjVmN64oaBgi8jv7xNFu5+c=
