encoding: utf-8
timezone: America/Los_Angeles

url: http://startup.singularityu.org

markdown: redcarpet

permalink: /blog/:month-:day-:year-:title.html
paginate: 10
paginate_path: "blog/page:num"

sass:
  style: :compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: [local]

gems:
  - jekyll-sitemap

collections:
  companies:
    output: true
    permalink: /portfolio/:path/
  mentors:
    output: true
    permalink: /mentor/:path/

exclude: [
  .DS_Store,
  .env,
  .sass-cache,
  Gemfile,
  Gemfile.lock,
  README.md,
  s3_website.yml,
  vendor,
  build.sh,
  deploy.sh
]
